#!/bin/bash

set -e

echo
echo "===> Build started at $(date)"
echo
START=$SECONDS

# Unconditionally print elapsed build time at exit
function finish {
  echo "===> Elapsed time: $(($SECONDS - $START)) seconds"
}
trap finish EXIT

echo "---> Preparing source..."
mkdir -p $SOURCE

cp -Rf /tmp/src/. $SOURCE

cd $SOURCE

echo "---> Downloading dependencies..."
go get -u github.com/FiloSottile/gvt
gvt restore

echo "---> Building application source..."
cd $SOURCE/cmd/paymentsvc
go build -o main
#go install main
#mv $GOPATH/bin/paymentsvc /usr/local/go/src/main
mv $SOURCE/cmd/paymentsvc/main $GOBIN/main
sudo setcap 'cap_net_bind_service=+ep' $GOBIN/main

#remove sudo from default user
sudo mv /etc/sudoers.bak /etc/sudoers

echo
echo "===> Build completed at $(date)"

# Fix source directory permissions
fix-permissions ./
